X2-6273 added smart breakdown item wrapping
xola/ui-kit pull request #246
Opened 2023-07-19 12:58 UTC by SemenStruchev

2023-07-21 07:56 UTC, KarthickXola requested changes
There are some lint fails

2023-07-24 09:37 UTC, manojx031 approved these changes

2024-02-26 04:51 UTC, rushi requested changes

2024-02-26 04:51 UTC, rushi commented on src/components/Breakdown.jsx
> +                            </span>
**Please hold on merging this PR** as it will cause conflicts with https://github.com/xola/ui-kit/pull/309

2025-02-06 11:37 UTC, rushi approved these changes

2025-02-06 11:37 UTC, merged