Setting default as no date for DatePickerPopover (X2-6907)
xola/ui-kit pull request #275
Opened 2023-10-13 11:45 UTC by shivbang

2023-10-16 10:38 UTC, shivbang commented
![image](https://github.com/xola/ui-kit/assets/51990693/8f5346a6-17d5-4eb5-9bca-83041ce08836)
![image](https://github.com/xola/ui-kit/assets/51990693/5db6f833-d1fb-464c-a6c0-fe40e98eba46)

2023-10-16 12:47 UTC, rushi requested changes

2023-10-16 13:36 UTC, shivbang commented on src/components/DatePicker/DatePicker.jsx
> +                    selectedDays={[selectedDays?.from, selectedDays]}
Earlier I mentioned that className that was not getting added to "from" value right - so I checked the examples on their website and made the change. I think it is something to do with initial from and to being null.

2023-10-17 09:21 UTC, rushi approved these changes

2023-10-17 09:21 UTC, rushi commented on src/components/DatePicker/DatePicker.jsx
> +    const thisValueIsValid = value && value.from && value.to;
`isValidValue`

2023-11-28 11:38 UTC, merged